---
title: "QALMRI"
author: "Ulrich"
format: html
editor_options: 
  chunk_output_type: console
---

## QUALMRI studie 1 - "5-week block periodization increases aerobic power in elite cross-country skiers"

Questions
What was the broad question being asked by this research project?

Er blokkperiodisering av utholdenhetstrening for langrennsløpere bedre enn tradisjonell trening?

What was the specific question being asked by this research project?

Er det forskjell i prestasjon mellom blokkperiodisering og tradisjonell trening for langrennsutøvere som nærmer seg konkurransesesong?


Alternatives 
What was the author’s hypothesis?

Hypotesen var at Blokkperiodisering (BP) ville ha større effect på målinger hva gjelder aerob kapasitet.  

What were the alternative hypotheses?



Logic 
What was the logic of the hypothesis?
i.e., if the hypothesis was true, what should we expect to happen?

Hvis hypotesen stemmer vil BP øke sin aerobe kapasitet mer enn TRAD

Methods 
What were the methods?

2 grupper, med likt utgangspunkt.
Pre og post test. 
Treningsintervensjon 5 uker(for kort?), samme volum, forkskjellig organisering.
Gruppene ble matchet på VO2MAX

Deltakere - for få?
19 eliteutøvere fra langrenn og skiskyting gjennomførte. 
BP 10(menn=7, kvinner = 3) ,  TRAD 9 (menn = 7, kvinner = 2)
 
VO2max-test og submaksimaltest for å teste arb.øk. på 4mmol/L
 
Alle verdier er presentert som gjennomsnitt ± standardavvik
ANOVA med Bonferroni ble brukt for å detektere forskjell innad og mellom gruppene post vs pre ved submakstesten på rulleski.
T.test, paret og uparet, ble burkt for sammenligne vo2maks, wmaks, w4mmol/L pre - post. 
ANCOVA? ta høyde for regresjon mot snittet?
effect størrelse gjort, men ikke power


Results 
What were the important results?

Regressjon mot snittet ikke tatt hensyn til??

Max watt er økte signf for BP vs TRAD
VO2max økte for BP, men ingen statistisk forskjell til TRAD. ANCOVA?
Watt ved 4mmol/L økte for BP og forskjellen var signifikant vs TRAD

Inferences 

 

What inferences about the questions and hypotheses can be
made base on the results?




QUALMRI studie 2 - "Block periodization of high-inetsity aerobic intervals provides superior training effects in trained cyclists"

Questions
What was the broad question being asked by this research project?
Kan BP være et bedre enn tradisjonell utholdenhetstrening?


What was the specific question being asked by this research project?
Sammenligne effekten mellom to forskjellige måter å organisere utholdenhetstrening på.


Alternatives 
What was the author’s hypothesis?

At BP vil gi overlegne adaptasjoner til VO2max, Wattmax og 2mmol/L

What were the alternative hypotheses?
At deltakerne som er med på forsøket er mer seriøse med kosthold, hvile og trening ved å delta på et prosjekt. Kanskje på grunn av økt motivasjon.


Logic 
What was the logic of the hypothesis?
i.e., if the hypothesis was true, what should we expect to happen?
Forskjell mellom gruppene. Høyere skår på målinger av prestasjonsvariabler enn controllgruppen.


Methods 
What were the methods?
Describe the study design. Use Hulley, (2013), Chapters 7-133 in your analysis.
Experimentelt design med to grupper, BP og TRAD.


Describe the sample and if the study defines the population.
19 frivillige godt trente syklister.
Ja, basert på at de ville ha med godt trente syklister. 


Describe the method of recruiting participants to the study. Did the authors 
justify their sample size (i.e. did they do a power calculation)?
Nei, bare effect size.

Fordelt på to grupper basert på VO2max, slik at gruppene har likest mulig utg.punkt. 


Describe how the study was conducted (what tests was performed when etc.)

Pre og post test.
Laktatprofil, trappetest med 5min og 50w økningm -> 4mmol/L eller høyere
VO2max- test. Trappetest med 1min og 25w økning til kadens < 60rpm

Describe the variables in the study, what variables relate to the question/hypothesis? 

VO2max - ml/kg/min
power output 2mmol/L 
Wmax - snittet av siste min på Vo2maxtesten
MAP
GE
Arbøk
BM

What methods did the authors use to make claims (what statistical tests were used)

Verdiene er snitt ± standardavvik
Effect størrelsen ble kalkulert msom cohens`d for si noe om den praktiske signifikansen til forbedringene i de to gruppene.
Uparet T-test ble brukt for å teste forskjellene mellom gruppene ved pre og treningsvolum. Uparet t-test ble brukt for å teste om det var noen relative forskjeller i forandring mellom gruppene. ANOVA one way analyse ble brukt for å sammenligne snittwatt fra hver HIT-økt mot følelse i beina etter endt uke, med Tukeys honestly significant differnece test for  post hoc analyse. two-way ANOVA ble brukt for å teste forskjellene mellom gruppene i snittwatt ved hver HIT og følelse i beina etter endt uke, med Bonferronis post-hoc test for å evaluere forskjellene. All analyse p <= 0,005 ble ansett som statistisk signifikant.

Results 
What were the important results?

Ingen forskjell i følelse i beina etter 4 uker
BP høyere snittwatt i HIT-økt i uke 4 sammenlignet med de fire første HIT-øktene i uke 1. 
TRAD ingen forskjell.
Bodymassadjusted Vo2max økte og Wattmax økte for BP.
TRAD Ingen forskjell.
Relative VO2maxforandringer var større i BP enn TRAD.
Ingen statistiske forskjeller i forandring i Wmax mellom gruppene
Teoretisk MAP økte for BP, men ingen forskjell mellom gruppene.
Moderat til stor effekt på relativ forbedring i Wmax, VO2max og MAP for BP mot TRAD
2mmol/L økte 10% hos BP, men ingen forskjell mellom gruppene



Inferences 


What inferences about the questions and hypotheses can be
made base on the results?

Det kan se ut som BP virker bedre enn TRAD.











QUALMRI studie 3- "Block periodization in alpine skiing: effects of 11-day HIT on VO2max and performance

Questions 
What was the broad question being asked by this research project?
Effekten av HIT-periodisering på VO2max


What was the specific question being asked by this research project?
Å teste 11-dagers HIT-blokk for å øke aerob kapasitet på junior-alpinister

Alternatives
What was the author’s hypothesis?
At en 11-dagers mikrosyklus med 15 HIT-økter vil øke Vo2max mer enn konvensjonell trening

What were the alternative hypotheses?
at det ikke gjør det?

Logic 
What was the logic of the hypothesis?
i.e., if the hypothesis was true, what should we expect to happen?
At Intervallgruppen (IT) får en større økning i VO2max enn kontroll

Methods 
What were the methods?


Describe the study design. Use Hulley, (2013), Chapters 7-133 in your analysis.
Experimentelt design.
To grupper, en experiment og en kontroll.




Describe the sample and if the study defines the population.

15 menn og 6 kvinner. Alpint juniornivå nasjonalt.


Describe the method of recruiting participants to the study. Did the authors justify their sample size (i.e. did they do a power calculation)?
Ble bare rekruttert står det. Bruker annen etisk forankring enn Rønnestad. KEK vs Helsisnki decl.

Describe how the study was conducted (what tests was performed when etc.)

Pre testing rett før start av intervensjon. Post testing 7 dager etter intervensjonen, til samme tid på døgnet for hver fp.
- Kroppsfett målt med 7-point skin fold method.
- Vertikal hopphøyde og peak power, ble målt på kraftplattform i hhvs SJ og CMJ
Utholdenhetstester ble utført på ergometersykkel
- Incrimental ramptest for å måle vo2max, 5-7 watt per 10s utfra fp`svekt
- Laktatmåling ved hvile, 4,6,8 og slutt (Lacmax) 
- RPE (BORG), hvert 2.min og ved slutt.
- Test slutt lavere enn 60rpm
- 3min hvile før max høyintensitet tid til utmattelses-test(tlim)
- TLIM begynte med 90s sykling på 40% for så rett opp til 90% av fp`s pre-PPO.




Describe the variables in the study, what variables relate to the question/hypothesis?

VO2max - høgeste 30s snitt
PPO- høyeste watt nådd på trappetesten
tid med høy hjertefrekvens
90s- bokshopptest- 44cm. Så mange hopp som mulig.



What methods did the authors use to make claims (what statistical tests were used)

- Alle resultat er preentert som snitt ± standardavvik.
- Forskjellen mellom gruppene ved baseline ble testet med two-tailed Students T.test for unpaired samples. 
- two- tailed students t-test for paired samples ble brukt for å teste signifikans i forskjeller pre-post, i gruppene og for kjønnsspesifikke forskjeller.
- Two-way ANOVA med repeterte målinger på to faktorer ble brukt for å sammenligne forskjeller mellom grupper og kjønn.
- Der det ble funnet signifikante forskjeller ble TUkeys` honestly significant difference post-hoc test brukt for å finne signifikante forskjeller??????
- Forskjeller i gruppenes treningsdata ble testet med en uparet two-tailed studenst t.test. 
- statistica ble brukt som software
- Signifikans grense ved p < 0,05.


Results
What were the important results?

- Treningsvolum lavere i kontroll enn i eskperimentgruppen
- Total training load ingen forskjell
- snittwatt økte i HIT-øktene for eksperimentell gruppe
- REL.vo2max økte signif. (6%) i exp. i forhold til kontroll.
- Absolute vo2max økte for begge gruppene.
- p-verdi brukt riktig? mannlige utøvere i exp. forbedret seg signifikant ifh menn i kontroll.
- ventilatorisk treshold? IT forbedret vo2max og power output på Vt2.
- 

Inferences What inferences about the questions and hypotheses can be
made base on the results?

Det kan se ut som BP i mikrosyklus funker bedre enn trad.







QUALMRI- studie 4 - "Effect of 12 weeks block periodization on performance and performance indices in well-trained cyclist"

Questions 
What was the broad question being asked by this research project?
(Hvordan påvirker blokkperiodisering VO2max?)


What was the specific question being asked by this research project?
Effecten av 12 uker med blokktrening på prestasjonsparametre for godt trente syklister.

Alternatives 
What was the author’s hypothesis?
At BP vil øke vo2max, laktatterskel, arb.øk. og snittwatt gjennom en 40-min all-out test sasmmenlignet med tradisjonell trening.

What were the alternative hypotheses?


Logic 
What was the logic of the hypothesis?
i.e., if the hypothesis was true, what should we expect to happen?
Signif Økning i parametre sammenlignet med TRAD



Methods 
What were the methods?

Describe the study design. Use Hulley, (2013), Chapters 7-13 in your analysis.
- Experimentelt design med kontroll-(n=7)  og eksp.-gruppe(n=8). 
- 


Describe the sample and if the study defines the population.
-15, mannlige syklister. Beskrevet som godt trente syklister.



Describe the method of recruiting participants to the study. Did the authors justify their sample size (i.e. did they do a power calculation)?
-


Describe how the study was conducted (what tests was performed when etc.)
- pre-post testing.
- treningsintervensjon med HIT blokklagt for BP og jevnt fordelt for TRAD.
- HR målt for hver økt og brukt som intensitetsstyring.
- zone 1,2,3.
- Blodlaktat 4mmol/L og GE trappetest. Fra 125w, opp 50w hvert 5min 
- Vo2makstest, trappetest, 25w + hvert min
- 40 min all out test. Høyest mulig snittwatt

Describe the variables in the study, what variables relate to the question/hypothesis?
- Vo2max
- Snittwatt på 40 min allout test
- vo2 og watt som korresponderte med 2mmol/L
- hb-masse
- 

What methods did the authors use to make claims (what statistical tests were used)
- Verdiene er snitt ± standardavvik
-Effect størrelsen  brukt som korrellasjons koeffesienter med r verdier fra (hopkins 2009).
- ANOVA viste ingen forskjell mellom gruppene pre-post, så t-tests med snitt Effect størrelse ble gjort ettersom det var forventet små forandringer hos godt trente syklister.
- cohens d ble brukt for å vurdere praktisk signif. 
- Forkjeller før og etter intervensjonen innenfor grupper ble vurdert med parede t-tester.
- For hver gruppe ble gjennomsnittlig kraftproduksjon og følelse i bein analysert ved bruk av enveis og toveis ANOVA.



Results 
What were the important results?

- BP førte til signifikant økning i målte utholdenhetsparametre som relativ VO2max og 2mmol/L og W.max
- 





Inferences 
What inferences about the questions and hypotheses can be
made base on the results?


QUALMRI- studie- 5 "Performance changes in world-class kayakers following two different training periodization models" 
 

 
Studien undersøkte om blokkperiodisering (BP) gir ytelsesfordeler over tradisjonell periodisering (TP) hos elitepadlere. Forfatterne fokuserte på hvordan ulike periodiseringsmodeller kan forbedre fysiologiske mål som VO₂ peak, padlehastighet og kraftutgang, med mål om å optimalisere treningseffektiviteten i konkurranseinnstillinger.

Større problem: Hvordan påvirker blokkperiodisering Vo2max og andre prestasjonsvariabler?

Spesifikke spørsmål: Gir BP lignende eller bedre ytelsesforbedringer sammenlignet med TP hos verdensklassepadlere?

Hypotese/Spørsmål: Forskningsspørsmålet er hypotese-drevet, og antar at BP kan forbedre nøkkelprestasjoner gjennom konsentrert treningsbelastning.

Alternative forklaringer: Faktorer som individuell treningshistorikk, restitusjonsprotokoller eller psykologisk tilpasning til treningsvariasjon kan påvirke resultatene.

Logisk linje: Introduksjonen beskriver trolig padlings ytelseskrav, peker på TP's ineffektivitet, og foreslår BP som en målrettet forbedring.

Studiedesign (ifølge Hulley, 2013): Studien fulgte et komparativt design, som evaluerte de to periodiseringsmetodene over to sesonger med pre- og postintervensjonstesting, i tråd med kvasieksperimentelle metoder.

Utvalg og populasjon: Ti elitepadlere deltok, representerende en populasjon av toppidrettsutøvere innen flattvannspadling.

Rekruttering og begrunnelse for utvalgsstørrelse: Studien oppga ingen styrkeberegning, sannsynligvis grunnet den begrensede tilgjengelige elitepopulasjonen.

Metoder og variabler: Hovedtester involverte fysiologiske målinger (VO₂ peak, ventilasjonsterskel) og prestasjonsmålinger (padlehastighet, kraftutgang). Disse variablene var sentrale for å evaluere BP’s effektivitet versus TP.

Statistisk analyse: Studien brukte standard inferensielle tester for å sammenligne BP- og TP-resultatene, inkludert gjentatte målinger for å observere endringer over flere testpunkter.

Hovedresultater: Begge periodiseringsmodeller forbedret prestasjonen, men BP var mer effektiv, og oppnådde lignende eller bedre resultater med halvparten av treningsvolumet sammenlignet med TP, noe som støttet den opprinnelige hypotesen.

Denne studien støtter BP som en verdifull treningsstrategi og gir innsikt i optimalisering av treningsopplegg for utholdenhetsidretter.



